server:
  port: 8081
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  main:
    allow-circular-references: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
